name: ETF Technical Indicators

on:
  schedule:
    - cron: '30 9 * * 2-6' # 9:30 AM UTC
  workflow_dispatch:

jobs:
  run-indicators:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./momentum_gauges
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pandas numpy gspread oauth2client polygon-api-client requests ta-lib
      - name: Run Technical Indicators
        env:
          SERVICE_ACCOUNT_KEY_GITHUB: ${{ secrets.SERVICE_ACCOUNT_KEY_GITHUB }}
          POLYGON_API_KEY_GITHUB: ${{ secrets.POLYGON_API_KEY_GITHUB }}
        run: python data_processing_mg_picks_technical_indicators.py # Ensure filename is correct